Graduate work: feature comments
RakhmaIs/java-explore-with-me pull request #8
Opened 2023-09-09 13:10 UTC by RakhmaIs

2023-09-10 18:46 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара мелких замечаний, которые необходимо исправить!
Желаю удачи!

2023-09-10 18:46 UTC, LexLippi commented on ewm-main-service/src/main/java/ru/practicum/main/event/dto/EventFullWithComment.java
> +@NoArgsConstructor
Здесь лучше использовать аннотацию `@Data`, она содержит в себе 4 из тех, что ты используешь

2023-09-10 18:46 UTC, LexLippi commented on ewm-main-service/src/main/java/ru/practicum/main/event/dto/EventFullWithCommentDto.java
> +public class EventFullWithCommentDto {
Аналогично тому, что уже писал

2023-09-10 18:46 UTC, LexLippi commented on ewm-main-service/src/main/resources/schema.sql
> +    text VARCHAR(1000)                          NOT NULL,
Лучше не называть аналогично типу данных

2023-09-10 18:46 UTC, LexLippi commented on ewm-main-service/src/main/resources/schema.sql
> +    text VARCHAR(1000)                          NOT NULL,
По возможности полям по которым мы осуществляем поиск стоит добавлять индексы:
https://www.postgresql.org/docs/current/indexes.html

2023-09-12 06:57 UTC, LexLippi commented
Привет!

Отличная работа!

Поздравляю с окончанием курса Java-разработчик!
Надеюсь наш курс был полезным для тебя и окажет влияние на твое будущее в профессии.

Желаю удачи!

2023-09-12 07:40 UTC, RakhmaIs commented
> Привет!
> 
> 
> 
> Отличная работа!
> 
> 
> 
> Поздравляю с окончанием курса Java-разработчик!
> 
> Надеюсь наш курс был полезным для тебя и окажет влияние на твое будущее в профессии.
> 
> 
> 
> Желаю удачи!

Привет, благодарю, спасибо тебе за грамотное и своевременное ревью и советы🤝

2023-09-12 13:15 UTC, merged